### ISSUE TITLE
Suggestion for different config scheme 

### ISSUE THREAD

**Issue by caktus-philip** [caktus/django_bread#24]
At present the bread constructor takes a lot of config params, and that only looks to grow. This is a suggestion of a way to keep that from growing to unmanageable size.

Each of the five views could have an associated config class, e.g. `BreadReadConfig`. The class' attributes would be the current ctor params that are applicable to read, like `form_class`, `view_class`, `base_template`, etc. There might be a 6th class for configuring things that aren't specific to a view.

The class would be populated with appropriate defaults during init. BREAD users could ignore these classes when they're happy with the defaults. A user who wants to change them can create an instance and only needs to change the attributes he cares about. Classes also offer some features (the ability to be subclassed, properties, etc.) that, at the moment, I can't see a use for but the flexibility is nice to have.

Another advantage to this is that it would organize the bread params into categories so that it would be obvious that e.g. the columns param applies to the browse view and no other.

**Comment by dpoirier** [comment]
Yes, things are rapidly getting unmanageable.

I'm a bit reluctant to add more custom classes, but how about this? Move the config params that are specific to a particular view to be attributes on the specific view classes like `ReadView` and `BrowseView` that we already have, then have users subclass those and pass the subclasses into Bread as needed. This is pretty similar to how the Django admin handles customization by subclassing ModelAdmin, so it should feel familiar.

That doesn't really help with the more global parameters, though. Maybe we should just handle those by subclassing the Bread class? Then we wouldn't need to pass in the view classes either, just override the attributes on the Bread class.

The result would be we'd only instantiate the Bread subclass so we can call get_urls() on it, and wouldn't need to pass any parameters when doing that. We could just do that in urls.py like we do with class-based views most of the time now.

views.py:

    class UserBrowseView(BrowseView):
        columns = [...]
        ....


    class UserBreadView(Bread):
        browse_view = UserBrowseView
        ...

urls.py:

    url(r'^', include(views.UserBreadView().get_urls())),

**Comment by caktus-philip** [comment]
That would work too, and it's probably less boilerplate than what I suggested.
