### ISSUE TITLE
Wrap browse actions in an if statement to make them customizable

### ISSUE THREAD

**Issue by caktus-philip** [caktus/django_bread#7]
I have a situation where I want to use the browse include template as-is, except that I want to change the actions available at the bottom of the page (from "Add" to "Add Foo" and "Add Bar"). Currently in order to do this I have to copy & paste the entire content of `templates/bread/includes/browse.html`, which is a lot.

One way to support this use case would be to wrap the actions section in an `if` statement that would be true by default, like so:

```
{% if not exclude_actions %}

  {% if may_add %}
    <a href="{% url bread.add_url_name %}">{% trans "Add" %}</a>
  {% elif debug %}
    You do not have add permission.
  {% endif %}

{% endif %}
```

Then the including template could include the browse template like so in order to kill the actions:
```
 <div>
   {% include "bread/includes/browse.html" with exclude_actions=True %}
 </div>
```

Concept swiped from http://stackoverflow.com/a/20220005

**Comment by dpoirier** [comment]
I was about to suggest using a block that could be overridden, then remembered that blocks only work for inheritance, not including.

I'm not thrilled with the current way we have templates set up anyway, in terms of allowing customization without repeating things. Is anyone fairly familiar with how the admin handles that?  It seems more flexible, especially in Django 1.8.
