### ISSUE TITLE
Next/previous page links can be wrong in the presence of filtering

### ISSUE THREAD

**Issue by dpoirier** [caktus/django_bread#9]
When we expect

http://127.0.0.1:8005/path/models/?thing=1&page=2

The link to the next/last page is 

http://127.0.0.1:8005/path/models/?thing=%5Bu%271%27%5D&page=2

which decodes to `thing=[u'1']`.

**Comment by trawick** [comment]
need doseq=True on the call to urlencode to build the args in request line format
